FTC2022-MakingAListAndCheckingItTwice/Controllers/TodoListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mime;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TodoListData;
using TodoListModels;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace FTC2022_MakingAListAndCheckingItTwice.Controllers
{
    [Authorize]
    public class TodoListController : Controller
    {
        private readonly TodoListDataContext _context;

        public TodoListController(TodoListDataContext context)
        {
            _context = context;
        }

        // TODO: Utilize this method to get the current user id:
        protected async Task<string> GetCurrentUserId()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return userId;
        }

        // GET: TodoList
        public async Task<IActionResult> Index()
        {
            var userId = await GetCurrentUserId();
            var items = await _context.ToDoItems.Where(x => x.UserId == userId).ToListAsync();
            return items != null ?
                        View(items) :
                        View(new List<TodoListItem>());
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AdminIndex()
        {
              return _context.ToDoItems != null ? 
                          View(await _context.ToDoItems.ToListAsync()) :
                          Problem("Entity set 'TodoListDataContext.ToDoItems'  is null.");
        }

        [Authorize(Roles = "Admin")]
        // GET: TodoList/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ToDoItems == null)
            {
                return NotFound();
            }

            var todoListItem = await _context.ToDoItems
                .FirstOrDefaultAsync(m => m.Id == id);
            if (todoListItem == null)
            {
                return NotFound();
            }

            return View(todoListItem);
        }

        [Authorize(Roles = "Admin")]
        // GET: TodoList/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TodoList/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,DetailText,IsCompleted,Status")] TodoListItem todoListItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(todoListItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(todoListItem);
        }

        // GET: TodoList/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ToDoItems == null)
            {
                return NotFound();
            }

            var todoListItem = await _context.ToDoItems.FindAsync(id);
            if (todoListItem == null)
            {
                return NotFound();
            }
            return View(todoListItem);
        }

        // POST: TodoList/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DetailText,IsCompleted,Status")] TodoListItem todoListItem)
        {
            if (id != todoListItem.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(todoListItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TodoListItemExists(todoListItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(todoListItem);
        }

        // GET: TodoList/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ToDoItems == null)
            {
                return NotFound();
            }

            var todoListItem = await _context.ToDoItems
                .FirstOrDefaultAsync(m => m.Id == id);
            if (todoListItem == null)
            {
                return NotFound();
            }

            return View(todoListItem);
        }

        // POST: TodoList/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ToDoItems == null)
            {
                return Problem("Entity set 'TodoListDataContext.ToDoItems'  is null.");
            }
            var todoListItem = await _context.ToDoItems.FindAsync(id);
            if (todoListItem != null)
            {
                _context.ToDoItems.Remove(todoListItem);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TodoListItemExists(int id)
        {
          return (_context.ToDoItems?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        /**************** Ajax Endpoints ************************/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateTodoListItemStatus(string detailId, string newStatus)
        {
            var success = int.TryParse(detailId, out int todoId);
            if (!success)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return Content("Todo Item Not Found!", MediaTypeNames.Text.Plain);
            }


            var userId = await GetCurrentUserId();
            var item = await _context.ToDoItems.SingleOrDefaultAsync(x => x.Id == todoId && x.UserId == userId);
            if (item is null)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return Content("Todo Item Not Found!", MediaTypeNames.Text.Plain);
            }

            success = int.TryParse(newStatus, out int updStatus);
            if (!success)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Content("Invalid Status", MediaTypeNames.Text.Plain);
            }

            var newItemStatus = (ItemStatus)updStatus;
            item.Status = newItemStatus;
            switch (newItemStatus)
            {
                case ItemStatus.NotStarted:
                case ItemStatus.InProgress:
                case ItemStatus.OnHold:
                    item.IsCompleted = false;
                    break;
                case ItemStatus.Abandoned:
                case ItemStatus.Completed:
                    item.IsCompleted = true;
                    break;
                default:
                    break;
            }
            await _context.SaveChangesAsync();
            Response.StatusCode = (int)HttpStatusCode.OK;
            return Content("Todo Item Updated!", MediaTypeNames.Text.Plain);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateTodoListItem(string detailId, string detailText)
        {
            var success = int.TryParse(detailId, out int todoId);
            if (!success)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return Content("Todo Item Not Found!", MediaTypeNames.Text.Plain);
            }

            var userId = await GetCurrentUserId();
            var item = await _context.ToDoItems.SingleOrDefaultAsync(x => x.Id == todoId && x.UserId == userId);
            if (item is null)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return Content("Record Not Found!", MediaTypeNames.Text.Plain);
            }

            item.DetailText = detailText;
            await _context.SaveChangesAsync();

            Response.StatusCode = (int)HttpStatusCode.OK;
            return Content("Record Updated!", MediaTypeNames.Text.Plain);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddTodoListItem(string text, string status)
        {
            if (string.IsNullOrWhiteSpace(text))
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Content("Invalid Details Text", MediaTypeNames.Text.Plain);
            }
            bool success = int.TryParse(status, out int updStatus);
            if (!success)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Content("Invalid Status", MediaTypeNames.Text.Plain);
            }

            var item = new TodoListItem();
            item.DetailText = text;
            item.UserId = await GetCurrentUserId();

            var newItemStatus = (ItemStatus)updStatus;
            item.Status = newItemStatus;

            switch (newItemStatus)
            {
                case ItemStatus.NotStarted:
                case ItemStatus.InProgress:
                case ItemStatus.OnHold:

FTC2022-MakingAListAndCheckingItTwice/Views/TodoList/AdminIndex.cshtml
@model IEnumerable<TodoListModels.TodoListItem>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DetailText)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsCompleted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DetailText)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsCompleted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

FTC2022-MakingAListAndCheckingItTwice/Views/TodoList/Create.cshtml
@using TodoListModels;
@model TodoListModels.TodoListItem

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TodoListItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DetailText" class="control-label"></label>
                <textarea asp-for="DetailText" class="form-control"></textarea>
                <span asp-validation-for="DetailText" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsCompleted" /> @Html.DisplayNameFor(model => model.IsCompleted)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" asp-items="@Html.GetEnumSelectList<ItemStatus>()" class="form-control"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FTC2022-MakingAListAndCheckingItTwice/Views/TodoList/Delete.cshtml
@model TodoListModels.TodoListItem

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TodoListItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DetailText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DetailText)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsCompleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsCompleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FTC2022-MakingAListAndCheckingItTwice/Views/TodoList/Details.cshtml
@model TodoListModels.TodoListItem

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TodoListItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DetailText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DetailText)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsCompleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsCompleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FTC2022-MakingAListAndCheckingItTwice/Views/TodoList/Edit.cshtml
@using TodoListModels;
@model TodoListModels.TodoListItem

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TodoListItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="DetailText" class="control-label"></label>
                <textarea asp-for="DetailText" class="form-control"></textarea>
                <span asp-validation-for="DetailText" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsCompleted" /> @Html.DisplayNameFor(model => model.IsCompleted)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" asp-items="@Html.GetEnumSelectList<ItemStatus>()" class="form-control"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FTC2022-MakingAListAndCheckingItTwice/Views/TodoList/Index.cshtml
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Xsrf
@using TodoListModels;
@model IEnumerable<TodoListModels.TodoListItem>
@functions
{
    public string GetAntiXsrfRequestToken()
    {
        return Xsrf.GetAndStoreTokens(Context).RequestToken;
    }
}
@{
    ViewData["Title"] = "My Tasks";
}
<div class="row">
    <div class="col-sm-2">
        <h1>@ViewData["Title"]:</h1>
    </div>
    <div class="col-sm-2"></div>
    <div class="col-sm-2">
        <button type="button" class="btn btn-success top-5" data-bs-toggle="modal" data-bs-target="#addTaskModal">
            Add Task
        </button>
    </div>
</div>

<div class="row">
    <div class="col-sm-6 align-content-center">
        <ul class="list-group">
            @foreach (var item in Model)
            {
                var bgClassBase = "task-list-group-item d-flex justify-content-between align-items-center";
                var bgClass = $"alert-primary {bgClassBase}";
                switch (item.Status)
                {
                    case ItemStatus.Abandoned:
                        bgClass = $"alert-danger {bgClassBase}";
                        break;
                    case ItemStatus.OnHold:
                        bgClass = $"alert-warning {bgClassBase}";
                        break;
                    case ItemStatus.Completed:
                        bgClass = $"alert-success {bgClassBase}";
                        break;
                    case ItemStatus.NotStarted:
                        bgClass = $"alert-info {bgClassBase}";
                        break;
                    default:
                        bgClass = $"alert-primary {bgClassBase}";
                        break;
                }

                <li class="@bgClass">

                    <span style="width:10%">@Html.DisplayFor(modelItem => item.IsCompleted)</span>
                    <span style="width:60%">
                        @Html.DisplayFor(modelItem => item.DetailText)
                    </span>
                    <span style="width:20%">
                        <select asp-for="@item.Status" asp-items="@Html.GetEnumSelectList<ItemStatus>()" class="form-control" onchange="updateTaskStatus($(this), @item.Id)"></select>
                    </span>
                    <button type="button" class="btn btn-sm btn-success" data-bs-toggle="modal" data-bs-target="#editTaskModal" data-bs-detailText="@item.DetailText" data-bs-detailId="@item.Id">
                        Edit
                    </button>
                    <button type="button" class="btn btn-sm btn-danger" onclick="deleteItem('@item.Id', '@item.DetailText');">Delete</button>
                </li>
            }
        </ul>
    </div>
</div>

<!-- add Task Modal -->
<div class="modal fade" id="addTaskModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Task</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                @{
                    var newTodo = new TodoListItem();
                }
                <div class="form-group">
                    <label asp-for="@newTodo.DetailText" class="control-label"></label>
                    <input id="newTodoDetailText" asp-for=" @newTodo.DetailText" class="form-control" />
                    <span asp-validation-for="@newTodo.DetailText" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@newTodo.Status" class="control-label"></label>
                    <select id="newTodoDetailStatus" asp-for="@newTodo.Status" asp-items="@Html.GetEnumSelectList<ItemStatus>()" class="form-control"></select>
                    <span asp-validation-for="@newTodo.Status" class="text-danger"></span>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                <button id="saveAddTask" type="button" class="btn btn-success">Save changes</button>
            </div>
        </div>
    </div>
</div>

<!-- edit Task Modal -->
<div class="modal fade" id="editTaskModal" tabindex="-1" aria-labelledby="exampleModalLabel2" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel2">Edit Task</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <textarea id="modalEditTaskDetail" style="width:100%;"></textarea>
                        <input id="modalEditTaskId" type="hidden" />
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                <button id="saveEditTask" type="button" class="btn btn-success">Save changes</button>
            </div>
        </div>
    </div>
</div>

@section scripts
    {
    <script>
        $(function (){
            $('#addTodoListItem').modal('hide');
        });

        $('#editTaskModal').on('show.bs.modal', function (event) {
            var button = event.relatedTarget;
            var detailText = button.getAttribute('data-bs-detailtext');
            var detailId = button.getAttribute('data-bs-detailid');
            //console.log("detailText", detailText);
            //console.log("detailId", detailId )
            var modal = $(this);
            $('#modalEditTaskDetail').val(detailText);
            $('#modalEditTaskId').val(detailId);
        })

        $('#saveEditTask').on('click', function () {
            var dText = $('#modalEditTaskDetail').val();
            var dId = $('#modalEditTaskId').val();
            console.log("Detail Text", dText);
            console.log("Detail Id", dId);
            $.ajax({
                url: '@Url.Action("UpdateTodoListItem", "TodoList")',
                type: 'POST',
                headers: { "RequestVerificationToken": "@GetAntiXsrfRequestToken()" },
                data: {"detailId": dId, "detailText": dText },
                success: function(result) {
                    $('#editTaskModal').modal('hide');
                    redirectToIndex();
                },
                error: function(result) {
                    alert("Failed to update todo item, please try again!");
                }
            });
        });

        function redirectToIndex(){
            //cheesy easy way to get the updates to show:
            var url = '@Url.Action("Index", "TodoList")';
            window.location.href = url;
        }

        function updateTaskStatus(e, taskId)
        {
            var newStatus = e.val();
            console.log("Task ID", taskId);
            console.log("Task Value", newStatus);
            $.ajax({
                url: '@Url.Action("UpdateTodoListItemStatus", "TodoList")',
                type: 'POST',
                headers: { "RequestVerificationToken": "@GetAntiXsrfRequestToken()" },
                data: { "detailId": taskId, "newStatus": newStatus },
                success: function(result) {
                    redirectToIndex();
                },
                error: function(result) {
                    alert("Failed to update status, please try again!");
                }
            });
        }

        $('#saveAddTask').on('click', function () {
            var newText = $('#newTodoDetailText').val();
            var newStatus = $('#newTodoDetailStatus').val();

            console.log("text", newText);
            console.log("status", newStatus);
            $.ajax({
                url: '@Url.Action("AddTodoListItem", "TodoList")',
                type: 'POST',
                headers: { "RequestVerificationToken": "@GetAntiXsrfRequestToken()" },
                data: { "text": newText, "status": newStatus },
                success: function(result) {
                    redirectToIndex();
                },
                error: function(result) {
                    alert("Failed to create new todo list item, please try again!");
                }
            });
        });

        function deleteItem(id, text) {
            var shouldDelete = confirm("Are you sure you want to delete todo list item [" + text + "]?");
            if (shouldDelete)
            {
                $.ajax({
                    url: '@Url.Action("Delete", "TodoList")',
                    type: 'POST',
                    headers: { "RequestVerificationToken": "@GetAntiXsrfRequestToken()" },
                    data: { "id": parseInt(id) },
                    success: function(result) {
                        redirectToIndex();
                    },
                    error: function(result) {
                        alert("Failed to delete the item, please try again!");
                    }
                });
            }
        }
    </script>
}